ktor:
    application:
        modules:
            - com.luxesoft.ApplicationKt.module
    deployment:
        port: 8080

mysql:
  url: "jdbc:mysql://localhost:3306/ktor_task_db"
  user: "root"
  password: "Pr0duct10n!"