ktor:
    application:
        modules:
            - com.luxesoft.ApplicationKt.module
    deployment:
        port: 8080

postgres:
  url: "jdbc:postgresql://localhost/ListingApp"
  user: "Postgres"
  password: "Pr0duction!"